//Emotion matrix idea
// 256 combinations
//Four dimensions of the model
//- Expectation- Null, Anticipation, Surprise, Confusion
    // Does this event match my model of the world
//- Threat (acute)- Null, Anger, Fear, Paralysis
    //A threat has been detected, should I flee or fight
//- ValueJudgment - Null, Disgust, Reverence (beauty), or ?Ambivalence?
    //An object that has qualities that produce emotion based on perceived worth
//- Contentment - Null, Joy, Sadness, Bittersweet
    //How we feel with the state of our lives
//Was torn on whether to organize this as an array or an object... array for now, maybe tailwind style 
//(with classnames hyphenated eg joy-anticipation) latter
//Matrix with order as listed above Expection is top layer, next is threat, then value, then contentment

//horror, suprise+ discust 
//devestation suprise + saddness + Paralysis
const emotionArray = 
[
    //Expectation
    // bittersweet- Saudade 
    //Null
    [
        //Threat
        //Null
        [
            //ValueJudgment
            //Null
            [
                //Contentment
                //Null
                
                    {
                        name:'Calm / Professional',//?name:'Impassive',
                        definition:"Basic emotion. Not feeling or showing emotion",
                        icon:"😑"
                    },
                //Joy
                    {
                        name:'Joy',
                        definition:"Basic emotion. A feeling of great pleasure and happiness",
                        icon:"😀"
                    },
                //Sadness
                    {
                        name:'Sad',
                        definition:"Basic emotion. A feeling of sadness and sorrow",
                        icon:"😢"
                    },
                //Bittersweet
               {
                    name:'Bittersweet',
                    definition:"A mix of Joy and sadness",
                    icon:"😔"
                }
            ],
            //Disgust
            [
                //Contentment
                //Null
                
                    {
                        name:'Disgust',
                        definition:"Revulsion or strong disapproval aroused by something unpleasant or offensive",
                        icon:"🤢"
                    },
                //Joy
                    {
                        name:'Morbid',
                        definition:"Characterized by or appealing to an abnormal and unhealthy interest in disturbing and unpleasant subjects, especially death and disease",
                        icon:"😈"
                    },
                //Sadness
                    {
                        name:'Remorse / Pity',
                        definition:"Depends on the source of the disgust, or its cause. Something is wrong with the world, and the person wishes they could fix it.",
                        icon:"😟"
                    },
                //Bittersweet
               {
                    name:'Morbid Pity',
                    definition:"Something is wrong with the world, and it makes you happy and sad at the same time",
                    icon:"👹"
                }
            ],
            //Reverence
            [
                //Contentment
                //Null
                
                    {
                        name:'Reverence',
                        definition:"Basic Emotion. The person or object is pure, beautiful or otherwise good for the world.",
                        icon:"😇"
                    },
                //Joy
                    {
                        name:'Love / Admire',
                        definition:"This person or object is good for the world, and good for you. You want them in your life",
                        icon:"🤗"
                    },
                //Sadness
                    {
                        name:'Resignation',
                        definition:"The state of the world is right, but it saddens you. Not necessarily good for you but it is for the world.",
                        icon:"🙇‍♂️"
                    },
                //Bittersweet
                {
                    name:'Respect',
                    definition:"Net positive, and of high quality. Not perfect but worthy of your admiration.",
                    icon:"🙏"
                }
            ],
            //Ambivalence
            [
                //Contentment
                //Null
                
                    {
                        name:'Ambivalence',
                        definition:"Obviously imperfect. It could be better, but is without value though. ",
                        icon:"😐"
                    },
                //Joy
                    {
                        name:'Contentment',
                        definition:"unknown",
                        icon:"🙂"
                    },
                //Sadness
                    {
                        name:'Discontent',
                        definition:"unknown",
                        icon:"😟"
                    },
                //Bittersweet
               {
                    name:'Mundane??',
                    definition:"It is as it is. The best of times; the worst of times.",
                    icon:"😶"
                }
            ]
        ],
        //Anger
        [
            //ValueJudgment
            //Null
            [
                //Contentment
                //Null
                
                    {
                        name:'Anger',
                        definition:"unknown",
                        icon:"😠"
                    },
                //Joy
                    {
                        name:'Cruel', //Pride//Victorious / ?
                        definition:"unknown",
                        icon:"😈" //?
                    },
                //Sadness
                    {
                        name:'Sullen', //Envy?
                        definition:"Sulking and Pouting",
                        icon:"😡"
                    },
                //Bittersweet
               {
                    name:'Menacing',
                    definition:"unknown",
                    icon:"👿"
                }
            ],
            //Disgust
            [
                //Contentment
                //Null
                
                    {
                        name:'Contempt',
                        definition:"unknown",
                        icon:"🙄"
                    },
                //Joy
                    {
                        name:'Derision',//Also Sarcasm
                        definition:"unknown",
                        icon:"😏"//?
                    },
                //Sadness
                    {
                        name:'Shame',
                        definition:"Either directed at someone or yourself",//?
                        icon:"😳"
                    },
                //Bittersweet
               {
                    name:'Scorn',//?
                    definition:"unknown",
                    icon:"😒"
                }
            ],
            //Reverence
            [
                //Contentment
                //Null
                
                    {
                        name:'Dominance',//Rightous AngerRighteous Indignation / 
                        definition:"unknown",
                        icon:"😤"//angry angel
                    },
                //Joy
                    {
                        name:'Pride', //?
                        definition:"unknown",
                        icon:"🤴"
                    },
                //Sadness
                    {
                        name:'Sullen Indignation',
                        definition:"unknown",
                        icon:"😾"
                    },
                //Bittersweet
               {
                    name:'Bittersweet Indignation',
                    definition:"unknown",
                    icon:"😼"
                }
            ],
            //Ambivalence
            [
                //Contentment
                //Null
                
                    {
                        name:'Disrespect',
                        definition:"unknown",
                        icon:"👉"
                    },
                //Joy
                    {
                        name:'Arrogant?',
                        definition:"unknown",
                        icon:"😒"
                    },
                //Sadness
                    {
                        name:'Offended',
                        definition:"unknown",
                        icon:"😤"
                    },
                //Bittersweet
               {
                    name:'unknown',
                    definition:"unknown",
                    icon:"unknown"
                }
            ]
        ],
        //Fear
        [
            //ValueJudgment
            //Null
            [
                //Contentment
                //Null
                
                    {
                        name:'Afraid',
                        definition:"unknown",
                        icon:"😨"
                    },
                //Joy
                    {
                        name:"Thrill", //?
                        definition: "Common on rollercoasters and other dangerous pursuits. Adrenaline Junkies seek this emotion",
                        icon:"😬"//"🤫"
                    },
                //Sadness
                    {
                        name:'Despair',
                        definition:"unknown",
                        icon:"😨"//?
                    },
                //Bittersweet
               {
                    name:'Nervous Excitement', //Exicited Terror? Feeling I got when I realized I was right about Covid
                    definition:"unknown",
                    icon:"😬"
                }
            ],
            //Disgust
            [
                //Contentment
                //Null
                
                    {
                        name:'Repugnance',
                        definition:"unknown",
                        icon:"🤢"
                    },
                //Joy
                    {
                        name:'Guilt', //?
                        definition:"unknown",
                        icon:"🤫"
                    },
                //Sadness
                    {
                        name:'Cringe',
                        definition:"unknown",
                        icon:"😖"
                    },
                    //Bittersweet
                {
                        name:'Gross?',
                        definition:"unknown",
                        icon:"🤢"
                }
            ],
            //Reverence
            [
                //Contentment
                //Null
                
                    {
                        name:'Submissive',
                        definition:"unknown",
                        icon:"🥺"
                    },
                //Joy
                    {
                        name:'Obedient',//?
                        definition:"unknown",
                        icon:"🙏"
                    },
                //Sadness
                    {
                        name:'Despondent',//???
                        definition:"unknown",
                        icon:"😓"
                    },
                //Bittersweet
               {
                    name:'Servile', //Beatpuppy syndrome? Idk
                    definition:"unknown",
                    icon:"🙇‍♂️"
                }
            ],
            //Ambivalence
            [
                //Contentment
                //Null
                
                    {
                        name:'Necessary Evil',
                        definition:"unknown",
                        icon:"🤕"
                    },
                //Joy
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Sadness
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Bittersweet
               {
                    name:'unknown',
                    definition:"unknown",
                    icon:"unknown"
                }
            ]
        ],
        //Paralysis
        [
            //ValueJudgment
            //Null
            [
                //Contentment
                //Null
                
                    {
                        name:'Paralysis',
                        definition:"unknown",
                        icon:"🥶"
                    },
                //Joy
                    {
                        name:'Spineless Cruelty',
                        definition:"unknown",
                        icon:"👿"
                    },
                //Sadness
                    {
                        name:'Angry Embarrassment',
                        definition:"unknown",
                        icon:"😡"
                    },
                //Bittersweet
               {
                    name:'Vexed?',
                    definition:"unknown",
                    icon:"😡"
                }
            ],
            //Disgust
            [
                //Contentment
                //Null
                
                    {
                        name:'Abhor?',
                        definition:"unknown",
                        icon:"🤢"
                    },
                //Joy
                    {
                        name:'Guilty Victory? ',
                        definition:"unknown",
                        icon:"😅"
                    },
                //Sadness
                {
                    name:'Vicarious Shame',
                    definition:"unknown",
                    icon:"😨"
                },
                    // {
                    //     name:'unknown',
                    //     definition:"unknown",
                    //     icon:"unknown"
                    // },
                //Bittersweet
                   {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
            ],
            //Reverence
            [
                //Contentment
                //Null
                
                    {
                        name:'Acceptance',
                        definition:"unknown",
                        icon:"🤝"
                    },
                //Joy
                    {
                        name:'Honor',//??
                        definition:"unknown",
                        icon:"👨‍⚖️"
                    },
                //Sadness
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Bittersweet
               {
                    name:'unknown',
                    definition:"unknown",
                    icon:"unknown"
                }
            ],
            //Ambivalence
            [
                //Contentment
                //Null
                
                    {
                        name:'Tolerance',
                        definition:"unknown",
                        icon:"😒"
                    },
                //Joy
                    {
                        name:'Mercy',
                        definition:"unknown",
                        icon:"✌"
                    },
                //Sadness
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Bittersweet
               {
                    name:'unknown',
                    definition:"unknown",
                    icon:"unknown"
                }
            ]
        ]
    ],
    //Anticipation
    // Nostalgia- Actipation + Bittersweet
    [
        //Threat
        //Null
        [
            //ValueJudgment
            //Null
            [
                //Contentment
                //Null
                
                    {
                        name:'Expectant/ Boredom',
                        definition:"Basic emotion. Pure expectation uncolored by other emotions. When unsurprised long enough it turns to boredom",
                        icon:"🥱" //?
                    },
                //Joy
                    {
                        name:'Optimism',
                        definition:"Expecting good things to happen",
                        icon:"😁" //
                    },
                //Sadness
                    {
                        name:'Pessimism',
                        definition:"Expecting good things to happen",
                        icon:"😩"
                    },
                //Bittersweet
               {
                    name:'Realism',
                    definition:"Expecting good and bad things to happen",
                    icon:"😫"
                }
            ],
            //Disgust
            [
                //Contentment
                //Null
                
                    {
                        name:'Cynicism',
                        definition:"unknown",
                        icon:"🤨"
                    },
                //Joy
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Sadness
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Bittersweet
               {
                    name:'unknown',
                    definition:"unknown",
                    icon:"unknown"
                }
            ],
            //Reverence
            [
                //Contentment
                //Null
                
                    {
                        name:'Hope / Faith',//?? Antipation of perfection
                        definition:"unknown",
                        icon:"🤞"
                    },
                //Joy
                    {
                        name:'Devotion',
                        definition:"Expecting to Love",
                        icon:"🥰"
                    },
                //Sadness
                    {
                        name:'Resignation',
                        definition:"unknown",
                        icon:"🙇‍♂️"
                    },
                //Bittersweet
               {
                    name:'Loyality',
                    definition:"unknown",
                    icon:"💂‍♂️"
                }
            ],
            //Ambivalence
            [
                //Contentment
                //Null
                
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Joy
                    {
                        name:'Dismissive Avoidant Love',
                        definition:"unknown",
                        icon:"🙄"
                    },
                //Sadness
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Bittersweet
               {
                    name:'Stoic',
                    definition:"unknown",
                    icon:"😶"
                }
            ]
        ],
        //Anger
        [
            //ValueJudgment
            //Null
            [
                //Contentment
                //Null
                
                    {
                        name:'Seethe',
                        definition:"unknown",
                        icon:"👿" //?
                    },
                //Joy
                    {
                        name:'Vengeance',
                        definition:"unknown",
                        icon:"😈"
                    },
                //Sadness
                    {
                        name:'Humiliation',
                        definition:"unknown",
                        icon:"😡"
                    },
                //Bittersweet
               {
                    name:'Destructive',
                    definition:"unknown",
                    icon:"👿"
                }
            ],
            //Disgust
            [
                //Contentment
                //Null
                
                    {
                        name:'Hate',
                        definition:"unknown",
                        icon:"👿"//?
                    },
                //Joy
                    {
                        name:'Malice',//?
                        definition:"unknown",
                        icon:"👺"
                    },
                //Sadness
                    {
                        name:'unknown',//'Future Shame?', //'deserved shame' //'expectant shame'
                        definition:"unknown",
                        icon:"😳"
                    },
                //Bittersweet
               {
                    name:'unknown',
                    definition:"unknown",
                    icon:"unknown"
                }
            ],
            //Reverence
            [
                //Contentment
                //Null
                
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Joy
                    {
                        name:'Paternalism',
                        definition:"unknown",
                        icon:"🤴"
                    },
                //Sadness
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Bittersweet
               {
                    name:'unknown',
                    definition:"unknown",
                    icon:"unknown"
                }
            ],
            //Ambivalence
            [
                //Contentment
                //Null
                
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Joy
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Sadness
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Bittersweet
               {
                    name:'unknown',
                    definition:"unknown",
                    icon:"unknown"
                }
            ]
        ],
        //Fear
        [
            //ValueJudgment
            //Null
            [
                //Contentment
                //Null
                
                    {
                        name:'Anxiety',
                        definition:"unknown",
                        icon:"😟"
                    },
                //Joy
                    {
                        name:'Ambition',//??
                        definition:"unknown",
                        icon:"🤑" 
                    },
                //Sadness
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Bittersweet
               {
                    name:'unknown',
                    definition:"unknown",
                    icon:"unknown"
                }
            ],
            //Disgust
            [
                //Contentment
                //Null
                
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Joy
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Sadness
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Bittersweet
               {
                    name:'unknown',
                    definition:"unknown",
                    icon:"unknown"
                }
            ],
            //Reverence
            [
                //Contentment
                //Null
                
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Joy
                    {
                        name:'Anxious Preoccupied Love',
                        definition:"unknown",
                        icon:"😓"
                    },
                //Sadness
                    {
                        name:'Reluctance',
                        definition:"unknown",
                        icon:"😧"
                    },
                //Bittersweet
               {
                    name:'unknown',
                    definition:"unknown",
                    icon:"unknown"
                }
            ],
            //Ambivalence
            [
                //Contentment
                //Null
                
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Joy
                    {
                        name:'Fearful Avoidant Love',
                        definition:"unknown",
                        icon:"🙄"
                    },
                //Sadness
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Bittersweet
               {
                    name:'unknown',
                    definition:"unknown",
                    icon:"unknown"
                }
            ]
        ],
        //Paralysis
        [
            //ValueJudgment
            //Null
            [
                //Contentment
                //Null
                
                    {
                        name:'Procrastinate',
                        definition:"unknown",
                        icon:"😓"
                    },
                //Joy
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Sadness
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Bittersweet
               {
                    name:'unknown',
                    definition:"unknown",
                    icon:"unknown"
                }
            ],
            //Disgust
            [
                //Contentment
                //Null
                
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Joy
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Sadness
                // {
                //     name:'Awkward Silence?',
                //     definition:"unknown",
                //     icon:"unknown"
                // },
                {
                    name:'unknown',
                    definition:"unknown",
                    icon:"unknown"
                },
                 
                //Bittersweet
               {
                    name:'unknown',
                    definition:"unknown",
                    icon:"unknown"
                }
            ],
            //Reverence
            [
                //Contentment
                //Null
                
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Joy
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Sadness
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Bittersweet
               {
                    name:'unknown',
                    definition:"unknown",
                    icon:"unknown"
                }
            ],
            //Ambivalence
            [
                //Contentment
                //Null
                
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Joy
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Sadness
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Bittersweet
               {
                    name:'unknown',
                    definition:"unknown",
                    icon:"unknown"
                }
            ]
        ]
    ],
    //Surprise
    [
        //Threat
        //Null
        [
            //ValueJudgment
            //Null
            [
                //Contentment
                //Null
                
                    {
                        name:'Surprise',
                        definition:"Basic emotion. Pure surprise uncolored by other emotions.",
                        icon:"😲"
                    },
                //Joy
                    {
                        name:'Delight',
                        definition:"Unexpected Joy",
                        icon:"🤣"
                    },
                //Sadness
                    {
                        name:'Disappointment',
                        definition:"An unpleasant surprise",
                        icon:"😞"
                    },
                //Bittersweet
               {
                    name:'Bittersweet Surprise?',
                    definition:"unknown",
                    icon:"unknown"
                }
            ],
            //Disgust
            [
                //Contentment
                //Null
                
                    {
                        name:"Sickening",//'Shock/ Disbelief ? Horror', 
                        definition:"unknown",
                        icon:"🤮"
                    },
                //Joy
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Sadness
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Bittersweet
               {
                    name:'unknown',
                    definition:"unknown",
                    icon:"unknown"
                }
            ],
            //Reverence
            [
                //Contentment
                //Null
                
                // {
                //     name:'unknown', //Awe //Moved curiousity to be a mix of JOy because it fit better
                //     definition:"unknown",
                //     icon:"unknown"
                // },
                {
                    name:'Alluring',
                    definition:"unknown",
                    icon:"🌹"
                },
                //Joy
                    {
                        name:'Enchanted', //?
                        definition:"unknown",
                        icon:"😍"
                    },
                  
                //Sadness
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Bittersweet
               {
                    name:'unknown',
                    definition:"unknown",
                    icon:"unknown"
                }
            ],
            //Ambivalence
            [
                //Contentment
                //Null
                
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Joy
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Sadness
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Bittersweet
               {
                    name:'unknown',
                    definition:"unknown",
                    icon:"unknown"
                }
            ]
        ],
        //Anger
        [
            //ValueJudgment
            //Null
            [
                //Contentment
                //Null
                
                    {
                        name:'Outrage',
                        definition:"unknown",
                        icon:"🤬"
                    },
                //Joy
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Sadness
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Bittersweet
               {
                    name:'unknown',
                    definition:"unknown",
                    icon:"unknown"
                }
            ],
            //Disgust
            [
                //Contentment
                //Null
                
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Joy
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Sadness
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Bittersweet
               {
                    name:'unknown',
                    definition:"unknown",
                    icon:"unknown"
                }
            ],
            //Reverence
            [
                //Contentment
                //Null
                
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Joy
                    {
                        name:'Valor',
                        definition:"unknown",
                        icon:"👮‍♂️"
                    },
                //Sadness
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Bittersweet
               {
                    name:'unknown',
                    definition:"unknown",
                    icon:"unknown"
                }
            ],
            //Ambivalence
            [
                //Contentment
                //Null
                
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Joy
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Sadness
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Bittersweet
               {
                    name:'unknown',
                    definition:"unknown",
                    icon:"unknown"
                }
            ]
        ],
        //Fear
        [
            //ValueJudgment
            //Null
            [
                //Contentment
                //Null
                
                    {
                        name:'Terror',
                        definition:"unknown",
                        icon:"😱"
                    },
                //Joy
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Sadness
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Bittersweet
               {
                    name:'unknown',
                    definition:"unknown",
                    icon:"unknown"
                }
            ],
            //Disgust
            [
                //Contentment
                //Null
                
                    {
                        name:'Horror' , //?
                        definition:"unknown",
                        icon:"😱"
                    },
                //Joy
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Sadness
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Bittersweet
               {
                    name:'unknown',
                    definition:"unknown",
                    icon:"unknown"
                }
            ],
            //Reverence
            [
                //Contentment
                //Null
                
                    {
                        name:'Awe', //?
                        definition:"unknown",
                        icon:"🤯"
                    },
                //Joy
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Sadness
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Bittersweet
               {
                    name:'unknown',
                    definition:"unknown",
                    icon:"unknown"
                }
            ],
            //Ambivalence
            [
                //Contentment
                //Null
                
                    {
                        name:'Daunting',
                        definition:"unknown",
                        icon:"😶"
                    },
                //Joy
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Sadness
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Bittersweet
               {
                    name:'unknown',
                    definition:"unknown",
                    icon:"unknown"
                }
            ]
        ],
        //Paralysis
        [
            //ValueJudgment
            //Null
            [
                //Contentment
                //Null
                
                    {
                        name:'Shock',
                        definition:"unknown",
                        icon:"😲"
                    },
                //Joy
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Sadness
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Bittersweet
               {
                    name:'unknown',
                    definition:"unknown",
                    icon:"unknown"
                }
            ],
            //Disgust
            [
                //Contentment
                //Null
                
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Joy
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Sadness
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Bittersweet
               {
                    name:'unknown',
                    definition:"unknown",
                    icon:"unknown"
                }
            ],
            //Reverence
            [
                //Contentment
                //Null
                
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Joy
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Sadness
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Bittersweet
               {
                    name:'unknown',
                    definition:"unknown",
                    icon:"unknown"
                }
            ],
            //Ambivalence
            [
                //Contentment
                //Null
                
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Joy
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Sadness
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Bittersweet
               {
                    name:'unknown',
                    definition:"unknown",
                    icon:"unknown"
                }
            ]
        ]
    ],
    //Some words that can be used
    // Doubt
    //Confusion
    // Melanchoy - Confused + Saddness
    [
        //Threat
        //Null
        [
            //ValueJudgment
            //Null
            [
                //Contentment
                //Null
                
                    {
                        name:'Confused',
                        definition:"unknown",
                        icon:"😕"
                    },
                //Joy
                    {
                        name:'Funny/ Humor',//Manic
                        definition:"unknown",
                        icon:"😁"
                    },
                //Sadness
                    {
                        name:'Melancholy',
                        definition:"unknown",
                        icon:"😢"
                    },
                //Bittersweet
               {
                    name:'Sad Jokes',//BipolarBittersweet Confusion
                    definition:"unknown",
                    icon:"😁/😢" //?
                }
            ],
            //Disgust
            [
                //Contentment
                //Null
                
                    {
                        name:'Sickening Doubt',
                        definition:"unknown",
                        icon:"🥴"
                    },
                //Joy
                    {
                        name:'Morbid Curiosity/ Dirty Jokes', //?
                        definition:"unknown",
                        icon:"😈" //demon with a monocule
                    },
                //Sadness
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Bittersweet
               {
                    name:'unknown',
                    definition:"unknown",
                    icon:"unknown"
                }
            ],
            //Reverence
            [
                //Contentment
                //Null
                
                    {
                        name:'Moral Doubt',
                        definition:"unknown",
                        icon:"😕"
                    },
                //Joy
                    {
                        name:'Curiosity', //?
                        definition:"unknown",
                        icon:"🔍"
                    },
                //Sadness
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Bittersweet
               {
                    name:'unknown',
                    definition:"unknown",
                    icon:"unknown"
                }
            ],
            //Ambivalence
            [
                //Contentment
                //Null
                
                    {
                        name:'Mixed Doubts',
                        definition:"unknown",
                        icon:"🤷‍♂️"
                    },
                //Joy
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Sadness
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Bittersweet
               {
                    name:'Cognitive Dissonance',
                    definition:"unknown",
                    icon:"🧠/😖"
                }
            ]
        ],
        //Anger
        [
            //ValueJudgment
            //Null
            [
                //Contentment
                //Null
                
                    {
                        name:'Unsettled',
                        definition:"unknown",
                        icon:"😤"//?
                    },
                //Joy
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Sadness
                    {
                        name:'Envy',
                        definition:"unknown",
                        icon:"😠"
                    },
                //Bittersweet
               {
                    name:'unknown',
                    definition:"unknown",
                    icon:"unknown"
                }
            ],
            //Disgust
            [
                //Contentment
                //Null
                
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Joy
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Sadness
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Bittersweet
               {
                    name:'unknown',
                    definition:"unknown",
                    icon:"unknown"
                }
            ],
            //Reverence
            [
                //Contentment
                //Null
                
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Joy
                    {
                        name:'Pique',
                        definition:"unknown",
                        icon:"😡/🤴"
                    },
                //Sadness
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Bittersweet
               {
                    name:'unknown',
                    definition:"unknown",
                    icon:"unknown"
                }
            ],
            //Ambivalence
            [
                //Contentment
                //Null
                
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Joy
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Sadness
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Bittersweet
               {
                    name:'unknown',
                    definition:"unknown",
                    icon:"unknown"
                }
            ]
        ],
        //Fear
        [
            //ValueJudgment
            //Null
            [
                //Contentment
                //Null
                
                    {
                        name:'Wary',
                        definition:"unknown",
                        icon:"🤔"
                    },
                //Joy
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Sadness
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Bittersweet
               {
                    name:'unknown',
                    definition:"unknown",
                    icon:"unknown"
                }
            ],
            //Disgust
            [
                //Contentment
                //Null
                
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Joy
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Sadness
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Bittersweet
               {
                    name:'unknown',
                    definition:"unknown",
                    icon:"unknown"
                }
            ],
            //Reverence
            [
                //Contentment
                //Null
                
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Joy
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Sadness
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Bittersweet
               {
                    name:'unknown',
                    definition:"unknown",
                    icon:"unknown"
                }
            ],
            //Ambivalence
            [
                //Contentment
                //Null
                
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Joy
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Sadness
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Bittersweet
               {
                    name:'unknown',
                    definition:"unknown",
                    icon:"unknown"
                }
            ]
        ],
        //Paralysis
        [
            //ValueJudgment
            //Null
            [
                //Contentment
                //Null
                
                    {
                        name:'Indecision',
                        definition:"unknown",
                        icon:"😖"
                    },
                //Joy
                    {
                        name:'Happy Disbelief?',
                        definition:"unknown",
                        icon:"😮"
                    },
                //Sadness
                    {
                        name:'Denial',
                        definition:"unknown",
                        icon:"😟"
                    },
                //Bittersweet
               {
                    name:'unknown',
                    definition:"unknown",
                    icon:"unknown"
                }
            ],
            //Disgust
            [
                //Contentment
                //Null
                
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Joy
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Sadness
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Bittersweet
               {
                    name:'unknown',
                    definition:"unknown",
                    icon:"unknown"
                }
            ],
            //Reverence
            [
                //Contentment
                //Null
                
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Joy
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Sadness
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Bittersweet
               {
                    name:'unknown',
                    definition:"unknown",
                    icon:"unknown"
                }
            ],
            //Ambivalence
            [
                //Contentment
                //Null
                
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Joy
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Sadness
                    {
                        name:'unknown',
                        definition:"unknown",
                        icon:"unknown"
                    },
                //Bittersweet
               {
                    name:'unknown',
                    definition:"unknown",
                    icon:"unknown"
                }
            ]
        ]
    ]
]

export default emotionArray


